//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class administrator_Default {
    
    /// <summary>
    /// login_C_S_R_F_inLoginDetected control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_Vulnerabilities_login_CSRFinLoginDetected login_C_S_R_F_inLoginDetected;
}
