USE [testsparker]
GO

--tblBlog sifirlaniyor
DROP TABLE [dbo].[tblBlog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblBlog](
	[blogId] [int] IDENTITY(1,1) NOT NULL,
	[blogUrl] [nvarchar](250) NULL,
	[blogSubject] [nvarchar](250) NULL,
	[blogContent] [text] NULL,
	[blogDate] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
TRUNCATE TABLE [dbo].[tblBlog]
--tblBlog data giriliyor
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
/**
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO

INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'Is Bitcoin really used by people','Yes. There is a growing number of businesses and individuals using Bitcoin. This includes brick and mortar businesses like restaurants, apartments, law firms, and popular online services such as Namecheap, WordPress, and Reddit. While Bitcoin remains a relatively new phenomenon, it is growing fast. At the end of August 2013, the value of all bitcoins in circulation exceeded US$ 1.5 billion with millions of dollars worth of bitcoins exchanged daily', CAST(N'2015-02-15 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES (N'What are the advantages of Bitcoin','Payment freedom - It is possible to send and receive any amount of money instantly anywhere in the world at any time. No bank holidays. No borders. No imposed limits. Bitcoin allows its users to be in full control of their money.', CAST(N'2009-05-14 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ([blogSubject], [blogContent], [blogDate]) VALUES ( N'How does Bitcoin work','From a user perspective, Bitcoin is nothing more than a mobile app or computer program that provides a personal Bitcoin wallet and allows a user to send and receive bitcoins with them. This is how Bitcoin works for most users.Behind the scenes, the Bitcoin network is sharing a public ledger called the "block chain". This ledger contains every transaction ever processed, allowing a user''s computer to verify the validity of each transaction. The authenticity of each transaction is protected by digital signatures corresponding to the sending addresses, allowing all users to have full control over sending bitcoins from their own Bitcoin addresses. In addition, anyone can process transactions using the computing power of specialized hardware and earn a reward in bitcoins for this service. This is often called "mining". To learn more about Bitcoin, you can consult the dedicated page and the original paper.', CAST(N'2008-05-18 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin fully virtual and immaterial','Bitcoin is as virtual as the credit cards and online banking networks people use everyday. Bitcoin can be used to pay online and in physical stores just like any other form of money. Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. Bitcoin balances are stored in a large distributed network, and they cannot be fraudulently altered by anybody. In other words, Bitcoin users have exclusive control over their funds and bitcoins cannot vanish just because they are virtual.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
INSERT [dbo].[tblBlog] ( [blogSubject], [blogContent], [blogDate]) VALUES ( N'Is Bitcoin anonymous','Bitcoin is designed to allow its users to send and receive payments with an acceptable level of privacy as well as any other form of money. However, Bitcoin is not anonymous and cannot offer the same level of privacy as cash. The use of Bitcoin leaves extensive public records. Various mechanisms exist to protect users'' privacy, and more are in development. However, there is still work to be done before these features are used correctly by most Bitcoin users.Some concerns have been raised that private transactions could be used for illegal purposes with Bitcoin. However, it is worth noting that Bitcoin will undoubtedly be subjected to similar regulations that are already in place inside existing financial systems. Bitcoin cannot be more anonymous than cash and it is not likely to prevent criminal investigations from being conducted. Additionally, Bitcoin is also designed to prevent a large range of financial crimes.', CAST(N'2012-10-10 00:00:00.000' AS DateTime))
GO
**/
--tblBlog icin url linkleri giriliyor
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  LOWER([blogSubject])+'-'+convert(nvarchar(250),[blogId])
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'?','')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'.','')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'ç','c')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'ğ','g')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'ı','i')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'ü','u')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'ş','s')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'ö','o')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),' ','-')
GO
UPDATE  [dbo].[tblBlog]  SET   [blogUrl] =  REPLACE(LOWER([blogUrl]),'--','-')
GO
--tblProducts sifirlaniyor
DROP TABLE [dbo].[tblProducts]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblProducts](
	[productTumbImageUrl] [nchar](255) NULL,
	[productPrice] [money] NULL,
	[productName] [nchar](255) NULL,
	[productDescription] [text] NULL,
	[productId] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
TRUNCATE TABLE [dbo].[tblProducts] 
--tblProduct data giriliyor
GO
INSERT [dbo].[tblProducts] ([productTumbImageUrl], [productPrice], [productName], [productDescription]) VALUES (N'/statics/1.jpg                                                                                                                                                                                                                                                ', 39.0000, N'Raspberry PI                                                                                                                                                                                                                                                   ', N'The Raspberry Pi is a series of credit card-sized single-board computers developed in the UK by the Raspberry Pi Foundation with the intention of promoting the teaching of basic computer science in schools.[4][5][6]
')
GO
INSERT [dbo].[tblProducts] ([productTumbImageUrl], [productPrice], [productName], [productDescription]) VALUES (N'/statics/2.jpg                                                                                                                                                                                                                                                ', 35.0000, N'Raspberry PI 2                                                                                                                                                                                                                                                 ', N'The original Raspberry Pi and Raspberry Pi 2 are manufactured in several board configurations through licensed manufacturing agreements with Newark element14 (Premier Farnell), RS Components and Egoman. These companies sell the Raspberry Pi online.[7] Egoman produces a version for distribution solely in China and Taiwan, which can be distinguished from other Pis by their red colouring and lack of FCC/CE marks. The hardware is the same across all manufacturers.
')
/**
GO
INSERT [dbo].[tblProducts] ([productTumbImageUrl], [productPrice], [productName], [productDescription]) VALUES (N'/statics/3.jpg                                                                                                                                                                                                                                                ', 55.0000, N'Raspberry Pi +                                                                                                                                                                                                                                                 ', N'The original Raspberry Pi is based on the Broadcom BCM2835 system on a chip (SoC),[1] which includes an ARM1176JZF-S 700 MHz processor, VideoCore IV GPU,[8] and was originally shipped with 256 megabytes of RAM, later upgraded (models B and B+) to 512 MB.[2][9] The system has Secure Digital (SD) (models A and B) or MicroSD (models A+ and B+) sockets for boot media and persistent storage.[10]
')
GO
INSERT [dbo].[tblProducts] ([productTumbImageUrl], [productPrice], [productName], [productDescription]) VALUES (N'/statics/4.jpg                                                                                                                                                                                                                                                ', 90.0000, N'Raspberry Pi #                                                                                                                                                                                                                                                 ', N'In 2014, the Raspberry Pi Foundation launched the Compute Module, which packages a BCM2835 with 512 MB RAM and an eMMC flash chip into a module for use as a part of embedded systems.[11]
')
GO
INSERT [dbo].[tblProducts] ([productTumbImageUrl], [productPrice], [productName], [productDescription]) VALUES (N'/statics/5.jpg                                                                                                                                                                                                                                                ', 50.0000, N'Raspberry Pi Light                                                                                                                                                                                                                                             ', N'none; 700 MHz ARM, 250 MHz core, 400 MHz SDRAM, 0 overvolt,
modest; 800 MHz ARM, 250 MHz core, 400 MHz SDRAM, 0 overvolt,
medium; 900 MHz ARM, 250 MHz core, 450 MHz SDRAM, 2 overvolt,
high; 950 MHz ARM, 250 MHz core, 450 MHz SDRAM, 6 overvolt,
turbo; 1000 MHz ARM, 500 MHz core, 600')
**/
GO
--tblComments sifirlaniyor
DROP TABLE [dbo].[tblComments]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblComments](
	[commentDate] [datetime] NULL,
	[commentAuthor] [nchar](255) NULL,
	[commentText] [text] NULL,
	[commentId] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
TRUNCATE TABLE  [dbo].[tblComments]
GO
--tblComments data giriliyor 
INSERT INTO [dbo].[tblComments]
           ([commentDate]
           ,[commentAuthor]
           ,[commentText])
     VALUES
           ('2015-02-13 00:00:00.000','Mustafa YALCIN','Yes. That''s new test site for Asp.Net!')
GO

INSERT INTO [dbo].[tblComments]
           ([commentDate]
           ,[commentAuthor]
           ,[commentText])
     VALUES
           ('2015-02-13 01:52:00.000','Onur YILMAZ','We apologize for the inconvenience during the works.')
GO

--tblBtcValues sifirlaniyor
DROP TABLE [dbo].[tblBtcValues]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblBtcValues](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BtcValueForUsd] [money] NULL
) ON [PRIMARY]
GO
TRUNCATE TABLE [dbo].[tblBtcValues]
GO
--tblBtcValues data giriliyor 
INSERT INTO tblBtcValues Values ('298.89');
GO
INSERT INTO tblBtcValues Values ('298.80');
GO
INSERT INTO tblBtcValues Values ('298.78');
GO
INSERT INTO tblBtcValues Values ('298.99');
GO
INSERT INTO tblBtcValues Values ('298.15');
GO
INSERT INTO tblBtcValues Values ('550.89');
GO
INSERT INTO tblBtcValues Values ('800.80');
GO
INSERT INTO tblBtcValues Values ('100.78');
GO
INSERT INTO tblBtcValues Values ('152.99');
GO
INSERT INTO tblBtcValues Values ('800.15');
GO
INSERT INTO tblBtcValues Values ('450.15');
GO
INSERT INTO tblBtcValues Values ('450.34');
GO
INSERT INTO tblBtcValues Values ('700.34');
GO
INSERT INTO tblBtcValues Values ('300.34');
GO
INSERT INTO tblBtcValues Values ('200.34');
GO
INSERT INTO tblBtcValues Values ('20.34');

--tblEmployees sifirlaniyor 
DROP TABLE [dbo].[tblEmployees]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tblEmployees](
	[employeeId] [int] IDENTITY(1,1) NOT NULL,
	[employeeName] [varchar](200) NULL,
	[employeeDescription] [text] NULL,
	[employeeImage] [varchar](250) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
--tblEmployees data giriliyor 
GO
SET IDENTITY_INSERT [dbo].[tblEmployees] ON 
GO
INSERT [dbo].[tblEmployees] ([employeeId], [employeeName], [employeeDescription], [employeeImage]) VALUES (1, N'Gabriel Shear', NULL, N'GabrielShear.jpg')
GO
INSERT [dbo].[tblEmployees] ([employeeId], [employeeName], [employeeDescription], [employeeImage]) VALUES (2, N'Stanley Jobson', NULL, N'StanleyJobson.jpg')
GO
SET IDENTITY_INSERT [dbo].[tblEmployees] OFF
GO
/****** Object:  Index [ClusteredIndex-20181220-120231]    Script Date: 12/20/2018 12:08:07 PM ******/
CREATE UNIQUE CLUSTERED INDEX [ClusteredIndex-20181220-120231] ON [dbo].[tblProducts]
(
	[productId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [NonClusteredIndex-20181220-120415]    Script Date: 12/20/2018 12:08:07 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20181220-120415] ON [dbo].[tblBlog]
(
	[blogId] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [NonClusteredIndex-20181220-120602]    Script Date: 12/20/2018 12:08:07 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20181220-120602] ON [dbo].[tblComments]
(
	[commentDate] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [NonClusteredIndex-20181220-120342]    Script Date: 12/20/2018 12:08:07 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20181220-120342] ON [dbo].[tblProducts]
(
	[productName] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [NonClusteredIndex-20181220-120449]    Script Date: 12/20/2018 12:08:07 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20181220-120449] ON [dbo].[tblProducts]
(
	[productPrice] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
EXEC sp_configure 'remote query timeout', 0 ;  
GO  
RECONFIGURE ;  